# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.blueprint.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'blueprint', 'function_path': 'animated_java:blueprint/animations/idle_nm/next_frame'}
execute if score @s aj.idle_nm.frame matches 85.. run scoreboard players set @s aj.idle_nm.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.idle_nm.frame
execute at @s run function animated_java:blueprint/animations/idle_nm/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.idle_nm.frame 1