# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.blueprint.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'blueprint', 'function_path': 'animated_java:blueprint/animations/idle_nm/play'}
tag @s add aj.blueprint.animation.idle_nm.playing
scoreboard players set @s aj.idle_nm.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:blueprint/animations/idle_nm/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only