# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:blueprint/animations/idle_nm/zzz/apply_frame {frame: 84}
scoreboard players add @s aj.idle_nm.frame 1