# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.blueprint.root] run return 0
execute on passengers if entity @s[tag=aj.blueprint.data] unless data entity @s {data:{rigHash: 'df3f588664ef9cc86c929f5aafa9a05edf7e068d3237d4d6b64d7d679ddc7ff5'}} on vehicle run function animated_java:blueprint/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1