# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.blueprint.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.blueprint.animation.idle.playing] run function animated_java:blueprint/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.blueprint.animation.idle_nm.playing] run function animated_java:blueprint/animations/idle_nm/zzz/on_tick
execute if entity @s[tag=aj.blueprint.animation.idlezedf.playing] run function animated_java:blueprint/animations/idlezedf/zzz/on_tick
execute if entity @s[tag=aj.blueprint.animation.idleori.playing] run function animated_java:blueprint/animations/idleori/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~