# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.text_display] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.bone] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.bone1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.head1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.body1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.right_arm1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_arm1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.left_arm1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_arm1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.right_leg1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_leg1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.left_leg1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_leg1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.text_display1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.text_display2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.head2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.body2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.right_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.left_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.right_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.left_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.bone3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.text_display4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.head3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.body3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.right_arm3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_arm3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.left_arm3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_arm3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.right_leg3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_leg3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.left_leg3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_leg3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.text_display3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.head4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.body4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.right_arm4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_arm4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.left_arm4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_arm4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.right_leg4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_leg4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.left_leg4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_leg4 set from storage aj:uuid main.out